# install-services.yml

---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: Installing apache
        apt: name=apache2 update_cache=yes state=present
      - name: Ensure apache starts
        service: name=apache2 state=started enabled=yes

  - hosts: webservers
    become: true
    tasks:
      - name: Installing services
        apt:
          name: 
            - apache2
            - php
            - mysql-server
          update_cache: yes
          state: present
      - name: Ensure apache starts
        service: name=apache2 state=started enabled=yes
      - name: Ensure mysql starts
        service: name=mysql state=started enabled=yes

  - hosts: local
    become: true
    tasks:
      - name: Installing services
        apt: name=mysql-client update_cache=yes state=present
      - name: Ensure mysql starts
        service: name=mysql state=started enabled=yes
