# setup-lb.yml
---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: enabled mod 1
        apache2_module: name=proxy state=present
      - name: enabled mod 2
        apache2_module: name=proxy_http state=present
      - name: enabled mod 3
        apache2_module: name=proxy_balancer state=present
      - name: enabled mod 4
        apache2_module: name=lbmethod_byrequests state=present

      - name: Creating template
        template:
          src: config/lb-config.j2
          dest: /etc/apache2/mods-enabled/proxy_balancer.conf
        notify: restart apache
    
    handlers:
      - name: restart apache
        service: name=apache2 state=restarted enabled=yes
